### ISSUE TITLE
Think about how to handle multiple signals

### ISSUE THREAD

**Issue by elray1** [cmu-delphi/epiprocess#10]
A common use case will be models that want to interact with multiple signals, e.g., cases, hospitalizations, deaths, and perhaps other covariates like mobility data. It would be ideal if this package supported this use case in a complete way. I see two concerns at the moment:

1. Representation of the data/enforced use of a single value column
2. Metadata tracking signal characteristics

Currently, the package requires a column to be named `value`, with the name of the signal stored as metadata. This is slightly awkward in a couple of ways:
- `value` is not a very meaningful term; we have to inspect the metadata to figure out what it is the data frame is tracking, rather than just looking at the column names.
- as discussed on our call today, if I want to track multiple signals, there are two possible ways to do that:
    (a) by adding extra columns tracking the things I want. But this doesn't seem ideal because
        - we essentially have to pick one of these columns as being "special" though there may not be reason to do so
        - metadata would only describe the variable in the value column, not the other columns
    (b) by using a list column for the value column. But this doesn't seem ideal because:
        - I think the user would need to unnest that list column before actually doing anything with the data like making plots or fitting models.
        - there may not be enough flexibility in the metadata to track information about all the variables in the data set

Here's a proposal:
 - drop the requirement that a column be named `value`
 - instead, in the metadata track something like `value_names`, a vector of names of columns in the data frame that contain signals of interest. This is required to have length at least 1
 - Track all other metadata in a named list, with names matching the entries of `value_names`. This has the advantage of optionally explicitly tracking things like issue dates and signal types separately for each signal in the data set. (For example, tracking issue dates separately may be beneficial if I'm modeling signals that don't all have regular release schedules that coincide on the same day.)

**Comment by brookslogan** [comment]
A couple other options I was coincidentally pondering a couple days ago, not sure they have advantages over the above though:
- make the metadata a tibble with columns equal to metadata (messier if we allow some signals to have different types of metadata than others).  Maybe add helper functions allowing tidyselect on columns based on the column metadata.
- use tibble-type column( group)s named based on the value of the most important metadata item, or nested tibble column groups based on multiple metadata items.  Allows access in model formulas as e.g. signals$jhucsse$signal1
- assign signal attributes to column attributes

**Comment by ryantibs** [comment]
Thanks @elray1 for jumping in with this great suggestion.  I like many aspects of this proposal!  

I'm just not sure I see yet a reason to have this completely replace the current `epi_signal` format, rather than be a viable alternative format.

I see advantages to both.  The disadvantages of the current format are the ones you listed.  

The disadvantage of the format that you're suggesting is that the column names themselves may have to contain info in some applications that you may want to use downstream, and extracting this info from the column names could be brittle.  For example, in the quantile forecasting case, we'd have column names like `quantile_level_0.1`, `quantile_level_0.5`, `quantile_level_0.9`, and so on, i.e., the quantile level is here part of the name.  (Or the quantile level is stored in the metadata?)  So extracting the quantile level for downstream use might be even more work than it would in the original list column format.

So here is a suggestion about we could proceed.

1. `epi_signal` format remains as it is currently, and `value` is a list column if you have multiple signals you want to track.   It's the "tersest" format.  
2. Calling `tidyr::unnest()` on the value column gives you an object in `epi_signal_long` format.  In the quantile forecasting example, you'd get two columns (say) `quantile_value` and `quantile_level`.
3. Calling `tidyr::unnest()` followed by `tidyr::pivot_wider()` gives you an object in `epi_signal_wide` format.  This is the one you're suggesting.   In the quantile forecasting example, you'd get columns (say) `quantile_level_0.1`, `quantile_level_0.5`, `quantile_level_0.9`, and so on.

Instead of subjecting the user to write their own wrangling code to go in between formats 1 and 2 and 3, we could just write some convenience functions (based on `tidyr::unnest()`, `tidyr::pivot_wider()`, etc.).  These convenience functions would also populate the metadata appropriately, so that, e.g., in wide format the names of the signal columns get stored in the metadata.

The advantage to supporting formats 1 and 2 and 3 is flexibility.  If you happen to like format 3 and I happen to like format 1, and they're both supported and we can easily transform back and forth between them, then we're both happy.  The disadvantage is maintenance cost.  If we have multiple formats that we support then it's more work to make sure that the package's functions work with all formats ...

What do you think?

**Comment by ryantibs** [comment]
After having slept on it, I think I already dislike my of having these three types suggestion purely for maintenance reasons.  It's going to be a lot of work to support `epi_signal_long` in particular.

Also, your suggested data structure, `epi_signal_wide` in my nomenclature is actually just purely more general than the current `epi_signal` format, because if we still allow for list columns, then of course I could still define a column called `value` with all the things I want in it.  

So my general take at this point is that we should go with the structure you're suggesting (but just keep it called `epi_signal`), allow for list columns, and if the user wants to play with long form data frames, then they can do it on their own accord but that won't be an official data type in `epitools`.

In the spirit of moving fast 🙂, I'm thinking about just implementing this later today.  Any reactions @elray1 @dajmcdon @jacobbien? (I would tag Logan but I'm hoping he's actually going to stop reading GitHub these next few days and take some time off!).

**Comment by elray1** [comment]
This sounds reasonable to me. A small hanging piece is whether we'd want to somehow track metadata for different signals in a list column (e.g. via a nested list?) so that they could be "unpacked" correctly when unnesting the column. But my instinct is to not worry about that for now.
