### ISSUE TITLE
Clicking on links for `epi_df` and `epi_archive` on the homepage's README gives 404 errors

### ISSUE THREAD

**Issue by kenmawer** [cmu-delphi/epiprocess#120]
On the [homepage](https://github.com/cmu-delphi/epiprocess), there are links for `epi_df` [here](https://github.com/cmu-delphi/epiprocess/blob/main/reference/epi_df.html) and `epi_archive` [here](https://github.com/cmu-delphi/epiprocess/blob/main/reference/epi_archive.html). However, they lead to pages that don't exist (i.e. give 404 errors).

**Comment by kenmawer** [comment]
Not an issue!

**Comment by brookslogan** [comment]
Thanks, Ken, for updating me on this issue.  Trying to summarize the closing and reopening reasons here:
- The `pkgdown.yaml` workflow uses `pkgdown` to build the `gh-pages` branch and the [doc site](https://cmu-delphi.github.io/epiprocess/).  `pkgdown` currently [uses](https://pkgdown.r-lib.org/reference/build_home.html#home-page) `README.md` as the home/landing page (previous link). The `epi_[df,archive]` links work there.  Thus the `README.md` works to build the site, and the issue was closed.
- The links are broken when viewing the `README.md` [directly on GitHub](https://github.com/cmu-delphi/epiprocess).  Some users may happen/prefer to land on GitHub when investigating a package, so this is still relevant.  -> reopen, but very minor (--> P3).

**Comment by dshemetov** [comment]
Closing due to issue age. Likely irrelevant.
