### ISSUE TITLE
Missing docs for archive.R

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epiprocess#132]
I think the documentation on `main` was behind. I just updated and force pushed. But I got a slew of warnings for undocumented R6 methods and functions in archive.R. Do we need to add those?

**Comment by brookslogan** [comment]
Tagged as P2 because while it seems pretty minor, it also may make use overlook actual issues with the R6 documentation.  Also the approach I suggested above is pretty easy to implement.

The complaints should appear as "warnings" in `devtools::check(vignettes=FALSE)`, but aren't tallied with the rest of the notes, warnings, and errors; they just appear somewhere in the console output.  The fix is to add the missing `@param` documentation for the R6 methods, something along the lines of
```
@param x same as in [`epix_wrapper_fn_name_for_this_method`]
```
(The `epix_wrapper_fn_name_for_this_method` function should already have been implemented, in `methods-epi_archive.R`.)
