### ISSUE TITLE
Warn if a non-`version` key is duplicated in `epi_df` or `epi_archive`

### ISSUE THREAD

**Issue by nmdefries** [cmu-delphi/epiprocess#154]
Currently, we do not check for distinct key values. This has some [potential uses](https://github.com/cmu-delphi/epiprocess/issues/89) but also introduces the opportunity to form unexpected or invalid archives. Continue allowing this behavior, but warn the user if duplicate keys exist when creating or adding to an archive or an `epi_df`.

**Comment by brookslogan** [comment]
#89 discusses this as well.  This issue is definitely the first step to do.  However, we may later decide to either (a) turn it into an error, or (b) make things actually work when there is a warning.  Actually, since this breaks the key `as_of` function, and thus also `epix_slide`, as well as the current `epix_merge` defaults (+ makes the user have to do post-processing to make non-defaults work) and stops the overhauled `epix_merge` in #101 from running, I think maybe we do want to just go ahead and make it an error.  Probably not helpful to construct an `epi_archive` with this condition if most things don't work and something works but requires manual hacking to fix up issues.

**Comment by brookslogan** [comment]
If we do keep it a warning, we need it to be a dire warning like "Current `epi_archive` methods were built assuming the key was a unique key; e.g., `epix_as_of` and `epix_slide` will give incorrect results, and other methods may also malfunction."

**Comment by brookslogan** [comment]
`epi_archive` side of this is handled in `lcb/grouped_epi_archive`.  Just made it a hard error since key methods like `as_of` malfunction otherwise.  Decision might differ for `epi_df`.

**Comment by brookslogan** [comment]
Being addressed in #519

**Comment by nmdefries** [comment]
Addressed in https://github.com/cmu-delphi/epiprocess/pull/519
