### ISSUE TITLE
Add plotting tools?

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/epiprocess#2]
Should we add plotting tools to this package?  It's not clear to me:

- Whether it belongs in this package versus a separate one (that does purely visualization, say `epivis` or `epiplot`).
- Should be done the way we did it in `covidcast` (even if it gets put in its own package).  Maybe just facilities for choropleth plots, but with a stronger reliance on built-in mapping software (some of what I did in `covidcast` got a bit hairy...).

**Comment by capnrefsmmat** [comment]
Hmm. For a general-purpose epidemic data tools package, the mapping problem is much, much harder. With covidcast, we knew in advance all of the geographic regions and levels that had to be supported. But with epitools, presumably someone might want to use it to make models of flu spread in the UK, or track meningitis in Germany, or whatever. Supporting choropleths worldwide at all plausible geographic levels would be quite difficult.

So if you do support it, you'd want to flip around the implementation. Have the user provide the data to plot *and the geography*, maybe as an `sf` data frame or something. The user is responsible for ensuring the geographic IDs they use in their epitools data match the IDs used in their geographic data, and the choropleth code just does the appropriate joins.

Then the question would be what the package is adding beyond what the user could do with `geom_sf`, given they have to bring their own `sf` data frame; we have a bunch of features to support better coloring and labeling in covidcast, but we'd want to think carefully about which features are essential and how to provide them in the simplest way.

As for time series plots, sure. I'd probably design it not to repeat anything ggplot does, e.g. the plot function shouldn't take a `title` argument because the user can use `labs`, that kind of thing. Maybe think of it as replacing

```r
ggplot(foo, aes(x = time_value, y = value)) +
  geom_line() +
  labs(x = "Date", y = "Number of cases")
```

with

```r
epiplot(foo) +
  labs(whatever)
```

where `epiplot` chooses the right `geom` and sets default titles/axes labels based on the signal metadata, but lets everything else be configured in the usual ggplot way with extra things added by `+`.
