### ISSUE TITLE
`epi_archive$as_of` still converts to tibble

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epiprocess#225]
We removed this conversion in `epi_archive$slide` in #212. Should we also remove here?

**Comment by brookslogan** [comment]
Yes, for consistency with other `epi_df` operations, I think `as_of` should
- if the result looks like it could be a valid `epi_df`, output an `epi_df`
- otherwise, output a tibble

and as far as I know, `as_of` should always be in the former situation.  Do you have an example where it doesn't output an `epi_df`?  I would have thought it would already produce only `epi_df`s due to [this line](https://github.com/cmu-delphi/epiprocess/blob/66d11727909390738af9dd62bd39c9ca523d9723/R/archive.R#L482).

**Comment by dajmcdon** [comment]
Ah, of course. Should have read more carefully.
