### ISSUE TITLE
`select` causes type conversion

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/epiprocess#388]
Calling `select(epi_data, -col_name)` on some `epi_df` converts it into a tibble. There are probably related issues, since this is only one of many dplyr verbs to support.

**Comment by brookslogan** [comment]
Can you please provide an example?  Sometimes this is intentional: e.g.,
```r
edf %>% select(geo_value)
```
is not a valid epi df (missing required columns).  Sometimes, it's gnarly to fix in general but maybe we could try hacking some fixes for every verb.... e.g.:
```r
edf %>% group_by(geo_value) %>% select(geo_value, time_value, value)
```
this we probably want to be a grouped `epi_df`.  See probably #223.

**Comment by dsweber2** [comment]
Appologies is this is a bit verbose; I was trying to add a temporary column, use it in a calculation, and then remove it.
```
################### setup###########
n_days <- 40
simple_dates <- seq(as.Date("2012-01-01"), by = "day", length.out = n_days)
rand_vals <- rnorm(n_days)
epi_data <- epiprocess::as_epi_df(rbind(tibble(
  geo_value = "al",
  time_value = simple_dates,
  a = 1:n_days,
  b = rand_vals
), tibble(
  geo_value = "ca",
  time_value = simple_dates,
  a = n_days:1,
  b = rand_vals + 10
)))

epi_data %>% mutate(temp_col = a^2) %>% mutate(perm_col = b-a^2) %>% select(-temp_col)
```
If we're adding checks as part of extending, insisting that select only changes the non-keys would make sense.
