### ISSUE TITLE
[DOC] Centralize and clarify documentation on mutation, compactification, and other footguns

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epiprocess#444]
There are a number of gotchas and footguns available for our users. We want to warn them, but we shouldn't overload them. Let's write a "cautions" document and link to that in the rest of the documentation.

Some previous ideas:
- It's generally unsafe for a user to modify epi_archive internals on their own. Use epiprocess functions whenever possible. `epi_archive$clobberable_versions_start <- ...` will not go through validation like it does on construction. Same goes for all the other attributes.
- Partial attribute matching can occur: `archive_cases_dv_subset$version` will partial match to `archive_cases_dv_subset$versions_end`.
- Maybe a "For data.table users:" section. ["Reseating"](https://github.com/cmu-delphi/epiprocess/pull/431#discussion_r1564661284) (not sure what this means)
- see the "Compactify" doc section after #431 is merged

**Comment by brookslogan** [comment]
- Reseat = mutate pointer to point to something different.
  - If you definitely reseat to an unaliased object, then you can do mutation of the "pointee" without as much worry, and can also "move" it / give ownership of it away assuming that you own the pointer & don't use it again.
  - If you potentially reseat, then you cannot do aliased mutation for the purpose of modifying the original pointee.

Compactify doc seems like an okay stop-gap.  Hoping that we can add a `filter` implementation, then encapsulate DT and provide only something like a `get_diff_data()` so that we can just compactify and not talk about it when people are constructing the archive.
