### ISSUE TITLE
`epi_df` structure

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epiprocess#482]
Possibly worth adding some sorting to `as_epi_df`. Some ideas,

1. Columns are always `time_value`, `geo_value`, additional keys, other columns
2. Rows always vary `time_value` fastest, then `geo_value`, etc.

For the second, perhaps add a `dplyr::arrange.epi_df()` method.

**Comment by brookslogan** [comment]
On point 1., I [polled](https://delphi-org.slack.com/archives/C028AUR6MV1/p1674673755987829?thread_ts=1674673612.084949&cid=C028AUR6MV1) some preferences regarding data-fetching *argument* ordering which might be relevant.

On point 2., I'm a little confused.  I think `arrange` already works properly on `epi_df`s; is it not working for you, or are you saying it should be forbidden?  Related: what do you think about these approaches?:
- A. `epi_df`s should always have rows sorted in this manner (so we should also make sure to maintain this order after any manipulations); `arrange.epi_df()` should output an explanatory error message.
- B. `epi_df`s should be sorted upon construction (maybe only by default, controlled by an `arrange` arg to `as_epi_df`), e.g., by calling `arrange()` at some point, but user should be able to later re-`arrange()` as they'd like
- C. Users should be able to choose either behavior by using a constructor argument (e.g., `keep_arranged`).

**Comment by dajmcdon** [comment]
Point 2. 

Hmmm, yes, `arrange()` works. I guess I was imagining a function (possibly different from `arrange()` that would rearrange to a standard ordering if requested. We don't even have this in our saved data, for example, compare `epiprocess::jhu_csse_daily_subset` to `epipredict::case_death_rate_subset`.

**Comment by dshemetov** [comment]
RE point 1, we looked into similar polling at some point when deciding for similar argument orders for epidatr and came to the similar ordering: location > time > other. Sorting by geo value and then time value seems most performant to me, since `group_by(geo_value)` is common for time series operations. Do we not already do this in the constructor? Seems like something we should do.

RE 2, I'm not really seeing the benefit of a "default" arrange function over a generic one that can accept different orders as arguments.
