### ISSUE TITLE
Simplify data.R

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epiprocess#544]
We can probably dispense with our manual delayed assign stuff and just use LazyData: TRUE as in [here](https://r-pkgs.org/data.html#sec-data-data), since we no longer have R6 to worry about.

**Comment by brookslogan** [comment]
#520 is going to transform how we load data and will close this.

**Comment by brookslogan** [comment]
#520 is merged.  Not the LazyData approach due to re-exporting from epidatasets, but does dispense with `delayed_assign_with_unregister_awareness` since we don't use R6 anymore, and is able to directly document with `delayedAssign`.  (We've noted some issues with workflow for updating documentation but that's probably for a separate Issue.)
